this._=this._||{};(function(_){var window=this;
try{
var ca,fa,ja,ka,ya,za;_.q=function(a){return function(){return _.ba[a].apply(this,arguments)}};_._DumpException=function(a){throw a;};_.ba=[];ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};fa="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global?window.global:this;
ja=function(a,b){if(b){for(var c=fa,d=a.split("."),e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];f=b(e);f!=e&&null!=f&&ca(c,d,{configurable:!0,writable:!0,value:f})}};ka=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
ja("String.prototype.repeat",function(a){return a?a:function(a){var b=ka(this,null,"repeat");if(0>a||1342177279<a)throw new window.RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=b),a>>>=1)b+=b;return d}});ja("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=ka(this,a,"startsWith");a+="";for(var e=b.length,f=a.length,h=Math.max(0,Math.min(c|0,b.length)),k=0;k<f&&h<e;)if(b[h++]!=a[k++])return!1;return k>=f}});_.la=_.la||{};_.r=this;
_.na=function(a){return void 0!==a};
_.pa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.qa=function(a){return"array"==_.pa(a)};_.t=function(a){return"string"==typeof a};_.ta="closure_uid_"+(1E9*Math.random()>>>0);ya=function(a,b,c){return a.call.apply(a.bind,arguments)};
za=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.u=function(a,b,c){_.u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ya:za;return _.u.apply(null,arguments)};
_.Aa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.Ca=Date.now||function(){return+new Date};_.A=function(a,b){var c=a.split("."),d=_.r;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.na(b)?d[e]=b:d=d[e]?d[e]:d[e]={}};
_.C=function(a,b){function c(){}c.prototype=b.prototype;a.S=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.jL=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.Da=function(a,b){return b};_.D=function(a,b){b=_.Da(a,b);_.A(a,b)};_.Ea=window.gadgets||{};_.Ga=window.osapi=window.osapi||{};_.google=window.google||{};window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{rms:"migrated"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},udc_webconsentflow:{url:"https://myaccount.google.com/webconsent?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},
requestCache:{enabled:!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:!0},transport:{isProxyShared:!0},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4}});
_.Ia=window;_.Ja=window.document;_.Na=_.Ia.location;_.Oa=/\[native code\]/;_.Pa=function(a,b,c){return a[b]=a[b]||c};_.Ra=function(){var a;if((a=Object.create)&&_.Oa.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.Sa=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.Ta=function(a,b){if(!a)throw Error(b||"");};_.Va=_.Pa(_.Ia,"gapi",{});
_.Wa=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.Ya=function(a,b,c){_.Xa(a,b,c,"add","at")};_.Xa=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.Za=_.Pa(_.Ia,"___jsl",_.Ra());_.Pa(_.Za,"I",0);_.Pa(_.Za,"hel",10);var $a,ab,cb,db,eb,gb;$a=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};ab=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};cb=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};db=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]&&b[c]&&"object"===typeof a[c]&&"object"===typeof b[c]&&!cb(a[c])&&!cb(b[c])?db(a[c],b[c]):b[c]&&"object"===typeof b[c]?(a[c]=cb(b[c])?[]:{},db(a[c],b[c])):a[c]=b[c])};
eb=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var b;try{b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return"object"===typeof b?b:{}}};
gb=function(a){ab(!0);var b=window.___gcfg,c=$a("cu");if(b&&b!==window.___gu){var d={};db(d,b);c.push(d);window.___gu=b}var b=$a("cu"),e=window.document.scripts||window.document.getElementsByTagName("script")||[],d=[],f=[];f.push.apply(f,$a("us"));for(var h=0;h<e.length;++h)for(var k=e[h],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",
!0),(f=d[e])?(h=f.nodeType,f=3==h||4==h?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=eb(f))&&b.push(f));a&&(d={},db(d,a),c.push(d));d=$a("cd");a=0;for(b=d.length;a<b;++a)db(ab(),d[a]);d=$a("ci");a=0;for(b=d.length;a<b;++a)db(ab(),d[a]);a=0;for(b=c.length;a<b;++a)db(ab(),c[a])};_.E=function(a,b){if(!a)return ab();for(var c=a.split("/"),d=ab(),e=0,f=c.length;d&&"object"===typeof d&&e<f;++e)d=d[c[e]];return e===c.length&&void 0!==d?d:b}; _.hb=function(a,b){var c=a;if("string"===typeof a){for(var d=c={},e=a.split("/"),f=0,h=e.length;f<h-1;++f)var k={},d=d[e[f]]=k;d[e[f]]=b}gb(c)};
var ib=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.Pa(_.Za,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};ib&&ib();gb();_.D("gapi.config.get",_.E);_.D("gapi.config.update",_.hb);
}catch(e){_._DumpException(e)}
try{
var qb,rb,wb,xb,yb,Ab,Bb,Cb,Db,Eb,Fb,Hb,Jb,Lb,Nb;_.lb=function(a){return!!a&&"object"===typeof a&&_.Oa.test(a.push)};_.mb=function(a,b,c){if(a){_.Ta(_.lb(a),"arrayForEach was called with a non array value");for(var d=0;d<a.length;d++)b.call(c,a[d],d)}};_.nb=function(a,b,c){if(a)if(_.lb(a))_.mb(a,b,c);else{_.Ta("object"===typeof a,"objectForEach was called with a non object value");c=c||a;for(var d in a)_.Sa(a,d)&&void 0!==a[d]&&b.call(c,a[d],d)}};
qb=function(a){a=a.sort();for(var b=[],c=void 0,d=0;d<a.length;d++){var e=a[d];e!=c&&b.push(e);c=e}return b};rb=function(){var a=[],b=_.Za.H;b&&_.nb(b,function(b){a.push.apply(a,b.L)});return qb(a)};_.sb=function(a){if(_.Oa.test(Object.keys))return Object.keys(a);var b=[],c;for(c in a)_.Sa(a,c)&&b.push(c);return b};Cb={};Db=0;Eb=_.Ra();Fb=_.Ra();Hb=function(a){return"number"===typeof a&&a>Math.random()};
_.Ib=function(a){if("undefined"===typeof wb){var b=_.E("report")||{},c=b.rate;Ab=b.timeout||1E3;xb=b.host||"https://plus.google.com";yb=b.path||"/_/widget/report";wb=[];Hb(c)&&(wb=b.apis||[]);var b=b.apiRate||{},d;for(d in b)Hb(b[d])&&wb.push(d)}for(d=0;d<wb.length;++d)if((new RegExp("^"+wb[d]+"$")).test(a))return!0;return!1};Jb=function(a){delete Cb[a]};
Lb=function(){Bb&&(_.Ia.clearTimeout(Bb),Bb=0);Bb=_.Ia.setTimeout(function(){var a;a=window.document.location;a=a.protocol+"//"+a.host+a.pathname;var b=_.sb(Fb).join(":");a=[xb,yb,"?api=",(0,window.encodeURIComponent)(b),"&url=",(0,window.encodeURIComponent)(a),"&loaded=",(0,window.encodeURIComponent)(rb().join(":"))].join("");Fb=_.Ra();var b=new window.Image,c=Db++;Cb[c]=b;b.onload=b.onerror=_.Aa(Jb,c);b.src=a;Bb=0},Ab)};_.Mb=function(a){Eb[a]||(Fb[a]=!0,Eb[a]=!0,Lb())};Nb=_.Da; _.Da=function(a,b){var c=Nb(a,b);"function"===typeof b&&_.Ib(a)&&(c=function(c){_.Mb(a);return b.apply(this,arguments)});return c};

}catch(e){_._DumpException(e)}
try{
_.rj=window.gapi&&window.gapi.util||{};
}catch(e){_._DumpException(e)}
try{
var sj=_.rj=_.rj||{};window.___jsl=window.___jsl||{};sj.qC={Hha:function(){return window.___jsl.bsh},gN:function(){return window.___jsl.h},NH:function(a){window.___jsl.bsh=a},x7:function(a){window.___jsl.h=a}};
}catch(e){_._DumpException(e)}
try{
var vj,wj;vj=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/u\/(\d)\//;wj=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/b\/(\d{10,})\//;_.xj=function(a){var b=_.E("googleapis.config/sessionIndex");null==b&&(b=window.__X_GOOG_AUTHUSER);if(null==b){var c=window.google;c&&(b=c.authuser)}null==b&&(a=a||window.location.href,b=_.Wa(a,"authuser")||null,null==b&&(b=(b=a.match(vj))?b[1]:null));return null==b?null:String(b)};
_.yj=function(a){var b=_.E("googleapis.config/sessionDelegate");null==b&&(b=(a=(a||window.location.href).match(wj))?a[1]:null);return null==b?null:String(b)};_.zj=function(a,b){var c=_.xj(a)||b,d=_.yj(a),e="";c&&(e+="u/"+c+"/");d&&(e+="b/"+d+"/");return e||null};

}catch(e){_._DumpException(e)}
try{
_.Aj=function(a){var b=String(a("immediate")||"");a=String(a("prompt")||"");return"true"===b||"none"===a};_.Bj=function(a){return _.E("enableMultilogin")&&a("cookie_policy")&&!_.Aj(a)?!0:!1};
_.Cj=function(a,b,c){a=String(a);if(null!=(_.Wa(a,"authuser")||null)||null!=(_.Wa(a,"hd")||null))return a;b=_.xj(b);if(c){var d=a,e=d.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(e&&e[0]){var f=e[1],h=e[4],k=e[5];e[3]=="/"+c&&(d=(f||"")+(h||"/")+(k||""))}if((e=d.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&e[0]){var f=e[2],l=e[4]||e[5],k=e[6];null!=b&&(d=(f||"")+"/"+c+"/"+(0,window.encodeURIComponent)(b)+(l||"/")+(k||""));return d}}null==
b?_.Bj(function(b){return _.Wa(a,b)||null})||(l=(0,window.encodeURIComponent)("authuser")+"=0"):l=b.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)(String(b)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(b)].join(""):["authuser=",(0,window.encodeURIComponent)(b)].join("");c=a.split("#");b=c[0].indexOf("?");0>b?c[0]=[c[0],"?",l].join(""):(d=[c[0]],b<c[0].length-1&&d.push("&"),d.push(l),c[0]=d.join("")); return d=c.join("#")};_.google.Nia=_.Cj;_.google.BE=_.xj;_.google.Vha=_.yj;_.google.Wha=_.zj;

}catch(e){_._DumpException(e)}
try{
var Dj=function(){this.Uk=-1};var Ej=function(){this.Uk=64;this.Ad=[];this.vC=[];this.eX=[];this.Vz=[];this.Vz[0]=128;for(var a=1;a<this.Uk;++a)this.Vz[a]=0;this.aB=this.fq=0;this.reset()};_.C(Ej,Dj);Ej.prototype.reset=function(){this.Ad[0]=1732584193;this.Ad[1]=4023233417;this.Ad[2]=2562383102;this.Ad[3]=271733878;this.Ad[4]=3285377520;this.aB=this.fq=0};
var Fj=function(a,b,c){c||(c=0);var d=a.eX;if(_.t(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.Ad[0];c=a.Ad[1];for(var h=a.Ad[2],k=a.Ad[3],l=a.Ad[4],m,e=0;80>e;e++)40>e?20>e?(f=k^c&(h^k),m=1518500249):(f=c^h^k,m=1859775393):60>e?(f=c&h|k&(c|h),m=2400959708):(f=c^h^k,m=3395469782),
f=(b<<5|b>>>27)+f+l+m+d[e]&4294967295,l=k,k=h,h=(c<<30|c>>>2)&4294967295,c=b,b=f;a.Ad[0]=a.Ad[0]+b&4294967295;a.Ad[1]=a.Ad[1]+c&4294967295;a.Ad[2]=a.Ad[2]+h&4294967295;a.Ad[3]=a.Ad[3]+k&4294967295;a.Ad[4]=a.Ad[4]+l&4294967295};
Ej.prototype.update=function(a,b){if(null!=a){_.na(b)||(b=a.length);for(var c=b-this.Uk,d=0,e=this.vC,f=this.fq;d<b;){if(0==f)for(;d<=c;)Fj(this,a,d),d+=this.Uk;if(_.t(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.Uk){Fj(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.Uk){Fj(this,e);f=0;break}}this.fq=f;this.aB+=b}};
Ej.prototype.digest=function(){var a=[],b=8*this.aB;56>this.fq?this.update(this.Vz,56-this.fq):this.update(this.Vz,this.Uk-(this.fq-56));for(var c=this.Uk-1;56<=c;c--)this.vC[c]=b&255,b/=256;Fj(this,this.vC);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.Ad[c]>>d&255,++b;return a};
_.Gj=function(){this.lr=new Ej};_.g=_.Gj.prototype;_.g.reset=function(){this.lr.reset()};_.g.wT=function(a){this.lr.update(a)};_.g.lM=function(){return this.lr.digest()};_.g.XI=function(a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var b=[],c=0,d=a.length;c<d;++c)b.push(a.charCodeAt(c));this.wT(b)};_.g.Ri=function(){for(var a=this.lM(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b};

}catch(e){_._DumpException(e)}
try{
_.Pl=function(a,b){a=a||{};for(var c in a)_.Sa(a,c)&&(b[c]=a[c])};
}catch(e){_._DumpException(e)}
try{
var Rl,Ql,Xl,Yl,Sl,Vl,Tl,Zl,Ul,Ql;_.Wl=function(){var a;Ql?(a=new _.Ia.Uint32Array(1),Rl.getRandomValues(a),a=Number("0."+a[0])):(a=Sl,a+=(0,window.parseInt)(Tl.substr(0,20),16),Tl=Ul(Tl),a/=Vl+Math.pow(16,20));return a};Rl=_.Ia.crypto;Ql=!1;Xl=0;Yl=0;Sl=1;Vl=0;Tl="";Zl=function(a){a=a||_.Ia.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%1E6*b;Sl=Sl*b%Vl;0<Xl&&++Yl==Xl&&_.Xa(_.Ia,"mousemove",Zl,"remove","de")};Ul=function(a){var b=new _.Gj;b.XI(a);return b.Ri()};
Ql=!!Rl&&"function"==typeof Rl.getRandomValues;Ql||(Vl=1E6*(window.screen.width*window.screen.width+window.screen.height),Tl=Ul(_.Ja.cookie+"|"+_.Ja.location+"|"+(new Date).getTime()+"|"+Math.random()),Xl=_.E("random/maxObserveMousemove")||0,0!=Xl&&_.Ya(_.Ia,"mousemove",Zl));

}catch(e){_._DumpException(e)}
try{
var $l,bm,cm,dm,em,fm,gm,hm,im,jm,mm,nm,om,pm,qm,rm;$l=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/;_.am=/^https?:\/\/[^\/%\\?#\s]+\/[^\s]*$/i;bm=function(a,b){var c=[];if(a)for(var d in a)if(_.Sa(a,d)&&null!=a[d]){var e=b?b(a[d]):a[d];c.push((0,window.encodeURIComponent)(d)+"="+(0,window.encodeURIComponent)(e))}return c};cm=function(a){return a.jL+(0<a.query.length?"?"+a.query.join("&"):"")+(0<a.dy.length?"#"+a.dy.join("&"):"")};
dm=function(a){a=a.match($l);var b=_.Ra();b.jL=a[1];b.query=a[3]?[a[3]]:[];b.dy=a[5]?[a[5]]:[];return b};em=/'/g;fm=/"/g;gm=/>/g;hm=/</g;im=/&/g;jm=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.km=function(a,b){var c="";2E3<b.length&&(c=b.substring(2E3),b=b.substring(0,2E3));var d=a.createElement("div"),e=a.createElement("a");e.href=b;d.appendChild(e);d.innerHTML=d.innerHTML;b=String(d.firstChild.href);d.parentNode&&d.parentNode.removeChild(d);return b+c};
_.lm=function(a,b,c,d){a=dm(a);a.query.push.apply(a.query,bm(b,d));a.dy.push.apply(a.dy,bm(c,d));return cm(a)};mm=function(a){return String(a).replace(im,"&amp;").replace(hm,"&lt;").replace(gm,"&gt;").replace(fm,"&quot;").replace(em,"&#39;")};om=function(){var a=_.Za.onl;if(!a){a=_.Ra();_.Za.onl=a;var b=_.Ra();a.e=function(a){var c=b[a];c&&(delete b[a],c())};a.a=function(a,d){b[a]=d};a.r=function(a){delete b[a]}}return a}; pm=function(a,b){var c=b.onload;return"function"===typeof c?(om().a(a,c),c):null};qm=function(a){_.Ta(/^\w+$/.test(a),"Unsupported id - "+a);om();return'onload="window.___jsl.onl.e(&#34;'+a+'&#34;)"'};rm=function(a){om().r(a)};
var tm,um,ym;_.sm={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};tm={allowtransparency:!0,onload:!0};um=0;_.vm=function(a,b){var c,d=0;do c=b.id||["I",um++,"_",(new Date).getTime()].join("");while(a.getElementById(c)&&5>++d);_.Ta(5>d,"Error creating iframe id");return c};_.wm=function(a,b){return a?b+"/"+a:""};
_.xm=function(a,b,c,d){var e={},f={};a.documentMode&&9>a.documentMode&&(e.hostiemode=a.documentMode);_.Pl(d.queryParams||{},e);_.Pl(d.fragmentParams||{},f);var h=d.connectWithQueryParams?e:f,k=d.pfname,l=_.Ra();l.id=c;l.parent=a.location.protocol+"//"+a.location.host;c=_.Wa(a.location.href,"parent");k=k||"";!k&&c&&(k=_.wm(_.Wa(a.location.href,"id",""),_.Wa(a.location.href,"pfname","")));l.pfname=k;_.Pl(l,h);(l=_.Wa(b,"rpctoken")||e.rpctoken||f.rpctoken)||(l=h.rpctoken=d.rpctoken||String(Math.round(1E8*
_.Wl())));d.rpctoken=l;h=a.location.href;a=_.Ra();(l=_.Wa(h,"_bsh",_.Za.bsh))&&(a._bsh=l);(h=_.Za.dpo?_.Za.h:_.Wa(h,"jsh",_.Za.h))&&(a.jsh=h);d.hintInFragment?_.Pl(a,f):_.Pl(a,e);return _.lm(b,e,f,d.paramsSerializer)};ym=function(a){_.Ta(!a||_.am.test(a),"Illegal url for new iframe - "+a)};
_.zm=function(a,b,c,d,e){ym(c.src);var f,h=pm(d,c),k=h?qm(d):"";try{window.document.all&&(f=a.createElement('<iframe frameborder="'+mm(String(c.frameborder))+'" scrolling="'+mm(String(c.scrolling))+'" '+k+' name="'+mm(String(c.name))+'"/>'))}catch(m){}finally{f||(f=a.createElement("iframe"),h&&(f.onload=function(){f.onload=null;h.call(this)},rm(d)))}for(var l in c)a=c[l],"style"===l&&"object"===typeof a?_.Pl(a,f.style):tm[l]||f.setAttribute(l,String(a));(l=e&&e.beforeNode||null)||e&&e.dontclear|| jm(b);b.insertBefore(f,l);f=l?l.previousSibling:b.lastChild;c.allowtransparency&&(f.allowTransparency=!0);return f};
var Am,Dm;Am=/^:[\w]+$/;_.Bm=/:([a-zA-Z_]+):/g;_.Cm=function(){var a=_.xj()||"0",b=_.yj(),c=_.zj(void 0,a),d=!1===_.E("isLoggedIn"),e=d?"_/im/":"";e&&(c="");var f=_.E("iframes/:socialhost:"),h=_.E("iframes/:im_socialhost:");return nm={socialhost:f,ctx_socialhost:d?h:f,session_index:a,session_delegate:b,session_prefix:c,im_prefix:e}};Dm=function(a,b){return _.Cm()[b]||""};_.Em=function(a){return _.km(_.Ja,a.replace(_.Bm,Dm))};
_.Fm=function(a){var b=a;Am.test(a)&&(b=_.E("iframes/"+b.substring(1)+"/url"),_.Ta(!!b,"Unknown iframe url config for - "+a));return _.Em(b)};
_.Gm=function(a,b,c){var d=c||{};c=d.attributes||{};_.Ta(!d.allowPost||!c.onload,"onload is not supported by post iframe");a=_.Fm(a);c=b.ownerDocument||_.Ja;var e=_.vm(c,d);a=_.xm(c,a,e,d);var f=_.Ra();_.Pl(_.sm,f);_.Pl(d.attributes,f);f.name=f.id=e;f.src=a;d.eurl=a;if((d||{}).allowPost&&2E3<a.length){var h=dm(a);f.src="";f["data-postorigin"]=a;a=_.zm(c,b,f,e);var k;if(-1!=window.navigator.userAgent.indexOf("WebKit")){k=a.contentWindow.document;k.open();var f=k.createElement("div"),l={},m=e+"_inner";
l.name=m;l.src="";l.style="display:none";_.zm(c,f,l,m,d)}f=(d=h.query[0])?d.split("&"):[];d=[];for(l=0;l<f.length;l++)m=f[l].split("=",2),d.push([(0,window.decodeURIComponent)(m[0]),(0,window.decodeURIComponent)(m[1])]);h.query=[];f=cm(h);_.Ta(_.am.test(f),"Invalid URL: "+f);h=c.createElement("form");h.action=f;h.method="POST";h.target=e;h.style.display="none";for(e=0;e<d.length;e++)f=c.createElement("input"),f.type="hidden",f.name=d[e][0],f.value=d[e][1],h.appendChild(f);b.appendChild(h);h.submit(); h.parentNode.removeChild(h);k&&k.close();b=a}else b=_.zm(c,b,f,e,d);return b};

}catch(e){_._DumpException(e)}
try{
_.tj=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a&&"android-app"!==a)throw Error("b");var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e|| "https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c};

}catch(e){_._DumpException(e)}
try{
_.rj.qb=function(a){return _.tj(a)};
}catch(e){_._DumpException(e)}
try{
_.F=_.F||{};
}catch(e){_._DumpException(e)}
try{
_.F=_.F||{};_.F.yz=function(a,b,c){for(var d=[],e=2,f=arguments.length;e<f;++e)d.push(arguments[e]);return function(){for(var c=d.slice(),e=0,f=arguments.length;e<f;++e)c.push(arguments[e]);return b.apply(a,c)}};_.F.Su=function(a){var b,c,d={};for(b=0;c=a[b];++b)d[c]=c;return d};

}catch(e){_._DumpException(e)}
try{
_.F=_.F||{};
(function(){function a(a,b){return String.fromCharCode(b)}var b={0:!1,10:!0,13:!0,34:!0,39:!0,60:!0,62:!0,92:!0,8232:!0,8233:!0,65282:!0,65287:!0,65308:!0,65310:!0,65340:!0};_.F.escape=function(a,b){if(a){if("string"===typeof a)return _.F.Xx(a);if("Array"===typeof a)for(var c=0,d=a.length;c<d;++c)a[c]=_.F.escape(a[c]);else if("object"===typeof a&&b){c={};for(d in a)a.hasOwnProperty(d)&&(c[_.F.Xx(d)]=_.F.escape(a[d],!0));return c}}return a};_.F.Xx=function(a){if(!a)return a;for(var c=[],e,f,h=0,k= a.length;h<k;++h)e=a.charCodeAt(h),f=b[e],!0===f?c.push("&#",e,";"):!1!==f&&c.push(a.charAt(h));return c.join("")};_.F.yja=function(b){return b?b.replace(/&#([0-9]+);/g,a):b}})();

}catch(e){_._DumpException(e)}
try{
_.Ol=_.Ol||{};_.Ol.w0=function(){var a=0,b=0;window.self.innerHeight?(a=window.self.innerWidth,b=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,b=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,b=window.document.body.clientHeight);return{width:a,height:b}};

}catch(e){_._DumpException(e)}
try{
_.Ol=_.Ol||{};
(function(){function a(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(RegExp.$1,10)}_.Ol.Vd=function(){var b=_.Ol.w0().height,c=window.document.body,d=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&d.scrollHeight)return d.scrollHeight!==b?d.scrollHeight:d.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){b=0;for(c=[window.document.body];0<c.length;){var e=c.shift(),d=e.childNodes;if("undefined"!==
typeof e.style){var f=e.style.overflowY;f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.overflowY:null);if("visible"!=f&&"inherit"!=f&&(f=e.style.height,f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.height:""),0<f.length&&"auto"!=f))continue}for(e=0;e<d.length;e++){f=d[e];if("undefined"!==typeof f.offsetTop&&"undefined"!==typeof f.offsetHeight)var h=f.offsetTop+f.offsetHeight+a(f,"margin-bottom"),b=Math.max(b,h);c.push(f)}}return b+a(window.document.body,"border-bottom")+ a(window.document.body,"margin-bottom")+a(window.document.body,"padding-bottom")}if(c&&d)return e=d.scrollHeight,f=d.offsetHeight,d.clientHeight!==f&&(e=c.scrollHeight,f=c.offsetHeight),e>b?e>f?e:f:e<f?e:f}})();

}catch(e){_._DumpException(e)}
try{
_.Rb=function(){function a(a,b){if(!(a<c)&&d)if(2===a&&d.warn)d.warn(b);else if(3===a&&d.error)try{d.error(b)}catch(h){}else d.log&&d.log(b)}var b=function(b){a(1,b)};_.Pb=function(b){a(2,b)};_.Ob=function(b){a(3,b)};_.Qb=function(){};b.INFO=1;b.WARNING=2;b.NONE=4;var c=1,d=window.console?window.console:window.opera?window.opera.postError:void 0;return b}();

}catch(e){_._DumpException(e)}
try{
_.F=_.F||{};(function(){var a=[];_.F.Ria=function(b){a.push(b)};_.F.fja=function(){for(var b=0,c=a.length;b<c;++b)a[b]()}})();
}catch(e){_._DumpException(e)}
try{
_.Sb=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;return-1};_.Ub=function(a,b){var c=_.Pa(_.Za,"watt",_.Ra());_.Pa(c,a,b)};_.F=_.F||{};
(function(){var a=null;_.F.Xc=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");for(var e=window.decodeURIComponent?window.decodeURIComponent:window.unescape,f=0,h=b.length;f<h;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k),k=b[f].substring(k+1),k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(m){}}}c&&(a=d);return d}; _.F.Xc()})();
_.D("gadgets.util.getUrlParameters",_.F.Xc);
}catch(e){_._DumpException(e)}
try{
_.Vb=window.console;_.Yb=function(a){_.Vb&&_.Vb.log&&_.Vb.log(a)};_.Zb=function(){};
}catch(e){_._DumpException(e)}
try{
_.$b=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&_.hb(a());return{register:function(a,c,d){d&&d(_.E())},get:function(a){return _.E(a)},update:function(a,c){if(c)throw"Config replacement is not supported";_.hb(a)},Pc:function(){}}}();
_.D("gadgets.config.register",_.$b.register);_.D("gadgets.config.get",_.$b.get);_.D("gadgets.config.init",_.$b.Pc);_.D("gadgets.config.update",_.$b.update);
}catch(e){_._DumpException(e)}
try{
var ac=function(a){return 10>a?"0"+a:a},bc={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},cc=function(a){var b,c,d;b=/[\"\\\x00-\x1f\x7f-\x9f]/g;if(void 0!==a){switch(typeof a){case "string":return b.test(a)?'"'+a.replace(b,function(a){var b=bc[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";
b=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){d=a.length;for(c=0;c<d;c+=1)b.push(cc(a[c])||"null");return"["+b.join(",")+"]"}for(c in a)!/___$/.test(c)&&_.Sa(a,c)&&"string"===typeof c&&(d=cc(a[c]))&&b.push(cc(c)+":"+d);return"{"+b.join(",")+"}"}return""}},dc=function(a){if(!a)return!1;if(/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))try{return eval("("+
a+")")}catch(b){}return!1},ec=!1,fc;try{ec=!!window.JSON&&'["a"]'===window.JSON.stringify(["a"])&&"a"===window.JSON.parse('["a"]')[0]}catch(a){}fc=function(a){try{return window.JSON.parse(a)}catch(b){return!1}};_.gc=ec?window.JSON.stringify:cc;_.hc=ec?fc:dc;fc||(Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",ac(this.getUTCMonth()+1),"-",ac(this.getUTCDate()),"T",ac(this.getUTCHours()),":",ac(this.getUTCMinutes()),":",ac(this.getUTCSeconds()),"Z"].join("")});

}catch(e){_._DumpException(e)}
try{
_.D("gadgets.json.stringify",_.gc);_.D("gadgets.json.parse",_.hc);_.Wa(_.Ia.location.href,"rpctoken")&&_.Ya(_.Ja,"unload",function(){});
}catch(e){_._DumpException(e)}
try{
var kc;_.ic=function(){var a=_.Ja.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.jc=function(a){if(_.ic())a();else{var b=!1,c=function(){if(!b)return b=!0,a.apply(this,arguments)};_.Ia.addEventListener?(_.Ia.addEventListener("load",c,!1),_.Ia.addEventListener("DOMContentLoaded",c,!1)):_.Ia.attachEvent&&(_.Ia.attachEvent("onreadystatechange",function(){_.ic()&&c.apply(this,arguments)}),_.Ia.attachEvent("onload",c))}};kc=kc||{};kc.tR=null; kc.RP=null;kc.Uy=null;kc.frameElement=null;
kc=kc||{};
kc.qJ||(kc.qJ=function(){function a(a){"undefined"!=typeof window.addEventListener?window.addEventListener("message",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onmessage",a);window.___jsl=window.___jsl||{};var b=window.___jsl;b.RPMQ=b.RPMQ||[];b.RPMQ.push(a)}function b(a){var b=(0,_.hc)(a.data);if(b&&b.f){(0,_.Qb)("gadgets.rpc.receive("+window.name+"): "+a.data);var d=_.G.zl(b.f);e&&("undefined"!==typeof a.origin?a.origin!==d:a.domain!==/^.+:\/\/([^:]+).*/.exec(d)[1])?_.Ob("Invalid rpc message origin. "+
d+" vs "+(a.origin||"")):c(b,a.origin)}}var c,d,e=!0;return{Gp:function(){return"wpm"},t3:function(){return!0},Pc:function(f,h){_.$b.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(e=!1)});c=f;d=h;a(b);d("..",!0);return!0},yd:function(a){d(a,!0);return!0},call:function(a,b,c){var d=_.G.zl(a),e=_.G.KK(a);d?window.setTimeout(function(){var a=(0,_.gc)(c);(0,_.Qb)("gadgets.rpc.send("+window.name+"): "+a);e.postMessage(a,d)},0):".."!=a&&_.Ob("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
kc=kc||{};
kc.by||(kc.by=function(){function a(a,b){K[b]=K[b]||function(){a.apply({},arguments)}}function b(){if(null===v&&window.document.body&&l){var a=l+"?cb="+Math.random()+"&origin="+B+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="___xpcswf" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+a+
'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;v=c.firstChild}++z;null!==w&&(null!==v||50<=z)?window.clearTimeout(w):w=window.setTimeout(b,100)}function c(){N[".."]||(k(".."),y++,50<=y&&null!==J?(window.clearTimeout(J),J=null):J=window.setTimeout(c,100))}function d(){if(null!==v&&v.setup)for(;0<x.length;){var a=x.shift(),b=a.w8;v.setup(a.Dr,".."===b?_.G.LB:b,".."===b?"INNER":"OUTER")}null!==w&&window.clearTimeout(w);w=null}function e(){N[".."]||null!==
J||(J=window.setTimeout(c,100))}function f(a,b,c){b=_.G.zl(a);var d=_.G.ql(a);v["sendMessage_"+(".."===a?_.G.LB:a)+"_"+d+"_"+(".."===a?"INNER":"OUTER")].call(v,(0,_.gc)(c),b);return!0}function h(a,b){var c=(0,_.hc)(a),d=c._scr;d?(p(d,!0),N[d]=!0,".."!==d&&k(d,!0)):window.setTimeout(function(){n(c,b)},0)}function k(a,b){var c=_.G.LB,d={};d._scr=b?"..":c;d._pnt=c;f(a,0,d)}var l=null,m=!1,n=null,p=null,v=null,x=[],w=null,z=0,y=0,J=null,N={},B=window.location.protocol+"//"+window.location.host,K;window.___jsl=
window.___jsl||{};K=window.___jsl._fm={};_.$b.register("rpc",null,function(a){m&&(l=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});a(d,"ready");a(e,"setupDone");a(h,"receiveMessage");return{Gp:function(){return"flash"},t3:function(){return!0},Pc:function(a,b){n=a;p=b;return m=!0},yd:function(a,c){x.push({Dr:c,w8:a});null===v&&null===w&&(w=window.setTimeout(b,100));return!0},call:f,kX:h,Yga:d,Zga:e}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.G&&_.G||(_.G=window.gadgets.rpc,_.G.config=_.G.config,_.G.register=_.G.register,_.G.unregister=_.G.unregister,_.G.$Q=_.G.registerDefault,_.G.uT=_.G.unregisterDefault,_.G.QM=_.G.forceParentVerifiable,_.G.call=_.G.call,_.G.Vt=_.G.getRelayUrl,_.G.rj=_.G.setRelayUrl,_.G.EA=_.G.setAuthToken,_.G.Mv=_.G.setupReceiver,_.G.ql=_.G.getAuthToken,_.G.gH=_.G.removeReceiver,_.G.uN=_.G.getRelayChannel,_.G.lA=_.G.receive,_.G.WQ=_.G.receiveSameDomain,_.G.qb=
_.G.getOrigin,_.G.zl=_.G.getTargetOrigin,_.G.KK=_.G._getTargetWin,_.G.jX=_.G._parseSiblingId);else{_.G=function(){function a(a,b){if(!oa[a]){var c=aa;b||(c=Ka);oa[a]=c;for(var d=ra[a]||[],e=0;e<d.length;++e){var f=d[e];f.t=N[a];c.call(a,f.f,f)}ra[a]=[]}}function b(){function a(){da=!0}Y||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),Y=!0)}function c(a,c,d,e,f){N[c]&&N[c]===d||(_.Ob("Invalid gadgets.rpc token. "+
N[c]+" vs "+d),Ha(c,2));f.onunload=function(){M[c]&&!da&&(Ha(c,1),_.G.gH(c))};b();e=(0,_.hc)((0,window.decodeURIComponent)(e))}function d(b,c){if(b&&"string"===typeof b.s&&"string"===typeof b.f&&b.a instanceof Array)if(N[b.f]&&N[b.f]!==b.t&&(_.Ob("Invalid gadgets.rpc token. "+N[b.f]+" vs "+b.t),Ha(b.f,2)),"__ack"===b.s)window.setTimeout(function(){a(b.f,!0)},0);else{b.c&&(b.callback=function(a){_.G.call(b.f,(b.g?"legacy__":"")+"__cb",null,b.c,a)});if(c){var d=e(c);b.origin=c;var f=b.r,h;try{h=e(f)}catch(ha){}f&&
h==d||(f=c);b.referer=f}d=(z[b.s]||z[""]).apply(b,b.a);b.c&&"undefined"!==typeof d&&_.G.call(b.f,"__cb",null,b.c,d)}}function e(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a)throw Error("b");
var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c}function f(a){if("/"==a.charAt(0)){var b=a.indexOf("|");return{id:0<b?a.substring(1,b):a.substring(1),origin:0<b?a.substring(b+1):null}}return null}function h(a){if("undefined"===typeof a||".."===a)return window.parent;var b=f(a);if(b)return window.top.frames[b.id];a=String(a);return(b=window.frames[a])?b:(b=window.document.getElementById(a))&&b.contentWindow?
b.contentWindow:null}function k(a,b){if(!0!==M[a]){"undefined"===typeof M[a]&&(M[a]=0);var c=h(a);".."!==a&&null==c||!0!==aa.yd(a,b)?!0!==M[a]&&10>M[a]++?window.setTimeout(function(){k(a,b)},500):(oa[a]=Ka,M[a]=!0):M[a]=!0}}function l(a){(a=y[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function m(a,b,c){b&&!/http(s)?:\/\/.+/.test(b)&&(0==b.indexOf("//")?b=window.location.protocol+
b:"/"==b.charAt(0)?b=window.location.protocol+"//"+window.location.host+b:-1==b.indexOf("://")&&(b=window.location.protocol+"//"+b));y[a]=b;"undefined"!==typeof c&&(J[a]=!!c)}function n(a,b){b=b||"";N[a]=String(b);k(a,b)}function p(a){a=(a.passReferrer||"").split(":",2);Ma=a[0]||"none";ea=a[1]||"origin"}function v(b){"true"===String(b.useLegacyProtocol)&&(aa=kc.Uy||Ka,aa.Pc(d,a))}function x(a,b){function c(c){c=c&&c.rpc||{};p(c);var d=c.parentRelayUrl||"",d=e(X.parent||b)+d;m("..",d,"true"===String(c.useLegacyProtocol));
v(c);n("..",a)}!X.parent&&b?c({}):_.$b.register("rpc",null,c)}function w(a,b,c){if(".."===a)x(c||X.rpctoken||X.ifpctok||"",b);else a:{var d=null;if("/"!=a.charAt(0)){if(!_.F)break a;d=window.document.getElementById(a);if(!d)throw Error("c`"+a);}d=d&&d.src;b=b||_.G.qb(d);m(a,b);b=_.F.Xc(d);n(a,c||b.rpctoken)}}var z={},y={},J={},N={},B=0,K={},M={},X={},oa={},ra={},Ma=null,ea=null,Z=window.top!==window.self,xa=window.name,Ha=function(){},sa=window.console,Fa=sa&&sa.log&&function(a){sa.log(a)}||function(){},
Ka=function(){function a(a){return function(){Fa(a+": call ignored")}}return{getCode:function(){return"noop"},isParentVerifiable:function(){return!0},init:a("init"),setup:a("setup"),call:a("call")}}();_.F&&(X=_.F.Xc());var da=!1,Y=!1,aa=function(){if("flash"==X.rpctx)return kc.by;if("rmr"==X.rpctx)return kc.tR;var a="function"===typeof window.postMessage?kc.qJ:"object"===typeof window.postMessage?kc.qJ:window.ActiveXObject?kc.by?kc.by:kc.RP?kc.RP:kc.Uy:0<window.navigator.userAgent.indexOf("WebKit")?
kc.tR:"Gecko"===window.navigator.product?kc.frameElement:kc.Uy;a||(a=Ka);return a}();z[""]=function(){Fa("Unknown RPC service: "+this.s)};z.__cb=function(a,b){var c=K[a];c&&(delete K[a],c.call(this,b))};return{config:function(a){"function"===typeof a.CR&&(Ha=a.CR)},register:function(a,b){if("__cb"===a||"__ack"===a)throw Error("d");if(""===a)throw Error("e");z[a]=b},unregister:function(a){if("__cb"===a||"__ack"===a)throw Error("f");if(""===a)throw Error("g");delete z[a]},$Q:function(a){z[""]=a},uT:function(){delete z[""]},
QM:function(){},call:function(a,b,c,d){a=a||"..";var e="..";".."===a?e=xa:"/"==a.charAt(0)&&(e=_.G.qb(window.location.href),e="/"+xa+(e?"|"+e:""));++B;c&&(K[B]=c);var h={s:b,f:e,c:c?B:0,a:Array.prototype.slice.call(arguments,3),t:N[a],l:!!J[a]},k;a:if("bidir"===Ma||"c2p"===Ma&&".."===a||"p2c"===Ma&&".."!==a){k=window.location.href;var l="?";if("query"===ea)l="#";else if("hash"===ea)break a;l=k.lastIndexOf(l);l=-1===l?k.length:l;k=k.substring(0,l)}else k=null;k&&(h.r=k);if(".."===a||null!=f(a)||window.document.getElementById(a))(k=
oa[a])||null===f(a)||(k=aa),0===b.indexOf("legacy__")&&(k=aa,h.s=b.substring(8),h.c=h.c?h.c:B),h.g=!0,h.r=e,k?(J[a]&&(k=kc.Uy),!1===k.call(a,e,h)&&(oa[a]=Ka,aa.call(a,e,h))):ra[a]?ra[a].push(h):ra[a]=[h]},Vt:l,rj:m,EA:n,Mv:w,ql:function(a){return N[a]},gH:function(a){delete y[a];delete J[a];delete N[a];delete M[a];delete oa[a]},uN:function(){return aa.Gp()},lA:function(a,b){4<a.length?aa.kX(a,d):c.apply(null,a.concat(b))},WQ:function(a){a.a=Array.prototype.slice.call(a.a);window.setTimeout(function(){d(a)},
0)},qb:e,zl:function(a){var b=l(a);a=b?b:(b=f(a))?b.origin:".."==a?X.parent:window.document.getElementById(a).src;return e(a)},Pc:function(){!1===aa.Pc(d,a)&&(aa=Ka);Z?w(".."):_.$b.register("rpc",null,function(a){a=a.rpc||{};p(a);v(a)})},KK:h,jX:f,o9:"__ack",LB:xa||"..",Vea:0,Uea:1,Tea:2}}();_.G.Pc()};
_.G.config({CR:function(a){throw Error("h`"+a);}});_.Qb=_.Zb;_.D("gadgets.rpc.config",_.G.config);_.D("gadgets.rpc.register",_.G.register);_.D("gadgets.rpc.unregister",_.G.unregister);_.D("gadgets.rpc.registerDefault",_.G.$Q);_.D("gadgets.rpc.unregisterDefault",_.G.uT);_.D("gadgets.rpc.forceParentVerifiable",_.G.QM);_.D("gadgets.rpc.call",_.G.call);_.D("gadgets.rpc.getRelayUrl",_.G.Vt);_.D("gadgets.rpc.setRelayUrl",_.G.rj);_.D("gadgets.rpc.setAuthToken",_.G.EA);_.D("gadgets.rpc.setupReceiver",_.G.Mv);_.D("gadgets.rpc.getAuthToken",_.G.ql); _.D("gadgets.rpc.removeReceiver",_.G.gH);_.D("gadgets.rpc.getRelayChannel",_.G.uN);_.D("gadgets.rpc.receive",_.G.lA);_.D("gadgets.rpc.receiveSameDomain",_.G.WQ);_.D("gadgets.rpc.getOrigin",_.G.qb);_.D("gadgets.rpc.getTargetOrigin",_.G.zl);

}catch(e){_._DumpException(e)}
try{
_.F=_.F||{};_.F.Ww=function(a,b,c,d){"undefined"!=typeof a.addEventListener?a.addEventListener(b,c,d):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+b,c):_.Pb("cannot attachBrowserEvent: "+b)};_.F.a6=function(a){var b=window;b.removeEventListener?b.removeEventListener("mousemove",a,!1):b.detachEvent?b.detachEvent("onmousemove",a):_.Pb("cannot removeBrowserEvent: mousemove")};

}catch(e){_._DumpException(e)}
try{
_.xk=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;n=m=0}function b(a){for(var b=h,c=0;64>c;c+=4)b[c/4]=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];for(c=16;80>c;c++)a=b[c-3]^b[c-8]^b[c-14]^b[c-16],b[c]=(a<<1|a>>>31)&4294967295;a=e[0];for(var d=e[1],f=e[2],k=e[3],l=e[4],m,p,c=0;80>c;c++)40>c?20>c?(m=k^d&(f^k),p=1518500249):(m=d^f^k,p=1859775393):60>c?(m=d&f|k&(d|f),p=2400959708):(m=d^f^k,p=3395469782),m=((a<<5|a>>>27)&4294967295)+m+l+p+b[c]&4294967295,
l=k,k=f,f=(d<<30|d>>>2)&4294967295,d=a,a=m;e[0]=e[0]+a&4294967295;e[1]=e[1]+d&4294967295;e[2]=e[2]+f&4294967295;e[3]=e[3]+k&4294967295;e[4]=e[4]+l&4294967295}function c(a,c){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var d=[],e=0,h=a.length;e<h;++e)d.push(a.charCodeAt(e));a=d}c||(c=a.length);d=0;if(0==m)for(;d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64;for(;d<c;)if(f[m++]=a[d++],n++,64==m)for(m=0,b(f);d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64}function d(){var a=[],
d=8*n;56>m?c(k,56-m):c(k,64-(m-56));for(var h=63;56<=h;h--)f[h]=d&255,d>>>=8;b(f);for(h=d=0;5>h;h++)for(var l=24;0<=l;l-=8)a[d++]=e[h]>>l&255;return a}for(var e=[],f=[],h=[],k=[128],l=1;64>l;++l)k[l]=0;var m,n;a();return{reset:a,update:c,digest:d,Ri:function(){for(var a=d(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b}}};
_.yk=function(){function a(a){var b=_.xk();b.update(a);return b.Ri()}var b=window.crypto;if(b&&"function"==typeof b.getRandomValues)return function(){var a=new window.Uint32Array(1);b.getRandomValues(a);return Number("0."+a[0])};var c=_.E("random/maxObserveMousemove");null==c&&(c=-1);var d=0,e=Math.random(),f=1,h=1E6*(window.screen.width*window.screen.width+window.screen.height),k=function(a){a=a||window.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%1E6*b;f=
f*b%h;0<c&&++d==c&&_.F.a6(k)};0!=c&&_.F.Ww(window,"mousemove",k,!1);var l=a(window.document.cookie+"|"+window.document.location+"|"+(new Date).getTime()+"|"+e);return function(){var b=f,b=b+(0,window.parseInt)(l.substr(0,20),16);l=a(l);return b/(h+Math.pow(16,20))}}();
_.D("shindig.random",_.yk);
}catch(e){_._DumpException(e)}
try{
_.H={};_.Uc={};window.iframer=_.Uc;
}catch(e){_._DumpException(e)}
try{
_.H.Wa=_.H.Wa||{};_.H.Wa.XX=function(a){try{return!!a.document}catch(b){}return!1};_.H.Wa.FN=function(a){var b=a.parent;return a!=b&&_.H.Wa.XX(b)?_.H.Wa.FN(b):a};_.H.Wa.dia=function(a){var b=a.userAgent||"";a=a.product||"";return 0!=b.indexOf("Opera")&&-1==b.indexOf("WebKit")&&"Gecko"==a&&0<b.indexOf("rv:1.")};

}catch(e){_._DumpException(e)}
try{
var er,fr,gr,ir,jr,kr,pr,qr,tr,ur,wr,xr,yr,Ar,Br,Cr;er=function(){_.H.CO++;return["I",_.H.CO,"_",(new Date).getTime()].join("")};fr=function(a){return a instanceof Array?a.join(","):a instanceof Object?(0,_.gc)(a):a};gr=function(){};ir=function(a){a&&a.match(hr)&&_.hb("googleapis.config/gcv",a)};jr=function(a){_.rj.qC.x7(a)};kr=function(a){_.rj.qC.NH(a)};_.lr=function(a,b){var c=b||{},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c};
_.nr=function(a,b,c,d,e){var f=[],h;for(h in a)if(a.hasOwnProperty(h)){var k=b,l=c,m=a[h],n=d,p=mr(h);p[k]=p[k]||{};n=_.F.yz(n,m);m._iframe_wrapped_rpc_&&(n._iframe_wrapped_rpc_=!0);p[k][l]=n;f.push(h)}if(e)for(h in _.H.Sp)_.H.Sp.hasOwnProperty(h)&&f.push(h);return f.join(",")};pr=function(a,b,c){var d={};if(a&&a._methods){a=a._methods.split(",");for(var e=0;e<a.length;e++){var f=a[e];d[f]=or(f,b,c)}}return d};
qr=function(a){if(a&&a.disableMultiLevelParentRelay)a=!1;else{var b;if(b=_.Uc&&_.Uc._open&&"inline"!=a.style&&!0!==a.inline)a=a.container,b=!(a&&("string"==typeof a&&window.document.getElementById(a)||window.document==(a.ownerDocument||a.document)));a=b}return a};tr=function(a,b){var c={},d=b.params||{},e;for(e in a)"#"==e.charAt(0)&&(c[e.substring(1)]=a[e]),0==e.indexOf("fr-")&&(c[e.substring(3)]=a[e]),"#"==d[e]&&(c[e]=a[e]);for(var f in c)delete a["fr-"+f],delete a["#"+f],delete a[f];return c};
ur=function(a){if(":"==a.charAt(0)){var b=_.E("iframes/"+a.substring(1));a={};_.Pl(b,a);(b=a.url)&&(a.url=_.Em(b));a.params||(a.params={});return a}return{url:_.Em(a)}};wr=function(a){function b(){}b.prototype=vr.prototype;a.prototype=new b};xr=function(a){return _.H.$v[a]};yr=function(a,b){_.H.$v[a]=b};Ar=function(a){a=a||{};"auto"===a.height&&(a.height=_.Ol.Vd());var b=window&&zr&&zr.Aa();b?b.oR(a.width||0,a.height||0):_.Uc&&_.Uc._resizeMe&&_.Uc._resizeMe(a)};Br=function(a){ir(a)};
Cr=function(a){var b=_.Wa(a.location.href,"urlindex");if(b=_.Pa(_.Za,"fUrl",[])[b]){var c=a.location.hash,b=b+(/#/.test(b)?c.replace(/^#/,"&"):c);a.location.replace(b)}};
if(window.ToolbarApi)zr=window.ToolbarApi,zr.Aa=window.ToolbarApi.getInstance,zr.prototype=window.ToolbarApi.prototype,_.g=zr.prototype,_.g.openWindow=zr.prototype.openWindow,_.g.FL=zr.prototype.closeWindow,_.g.pS=zr.prototype.setOnCloseHandler,_.g.uL=zr.prototype.canClosePopup,_.g.oR=zr.prototype.resizeWindow;else{var zr=function(){},Dr=null;zr.Aa=function(){!Dr&&window.external&&window.external.GTB_IsToolbar&&(Dr=new zr);return Dr};_.g=zr.prototype;_.g.openWindow=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.g.FL=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.g.pS=function(a,b){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,b)};_.g.uL=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.g.oR=function(a,b){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,b)};window.ToolbarApi=zr;window.ToolbarApi.getInstance=zr.Aa};
var Er=function(){_.G.register("_noop_echo",function(){this.callback(_.H.Y_(_.H.Fl[this.f]))})},Fr=function(){window.setTimeout(function(){_.G.call("..","_noop_echo",_.H.n5)},0)},or=function(a,b,c){var d=function(d){var e=Array.prototype.slice.call(arguments,0),h=e[e.length-1];if("function"===typeof h){var k=h;e.pop()}e.unshift(b,a,k,c);_.G.call.apply(_.G,e)};d._iframe_wrapped_rpc_=!0;return d},mr=function(a){_.H.nA[a]||(_.H.nA[a]={},_.G.register(a,function(b,c){var d=this.f;if(!("string"!=typeof b||
b in{}||d in{})){var e=this.callback,f=_.H.nA[a][d],h;f&&Object.hasOwnProperty.call(f,b)?h=f[b]:Object.hasOwnProperty.call(_.H.Sp,a)&&(h=_.H.Sp[a]);if(h)return d=Array.prototype.slice.call(arguments,1),h._iframe_wrapped_rpc_&&e&&d.push(e),h.apply({},d)}_.Ob(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',b,'" from frame "',d,'".'].join(""));return null}));return _.H.nA[a]};
_.H.TX=function(a,b,c){var d=Array.prototype.slice.call(arguments);_.H.qN(function(a){a.sameOrigin&&(d.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.G.call.apply(_.G,d))})};_.H.V5=function(a,b){_.G.register(a,b)};
var hr=/^[-_.0-9A-Za-z]+$/,Gr={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"},Hr={onBeforeParentOpen:"beforeparentopen"},Ir={onOpen:function(a){var b=a.wc();a.Jg(b.container||b.element);return a},onClose:function(a){a.remove()}};_.H.Ip=function(a){var b=_.Ra();_.Pl(_.sm,b);_.Pl(a,b);return b};
var vr=function(a,b,c,d,e,f,h,k){this.config=ur(a);this.openParams=this.hv=b||{};this.params=c||{};this.methods=d;this.UA=!1;Jr(this,b.style);this.Gs={};Kr(this,function(){var a;(a=this.hv.style)&&_.H.$v[a]?a=_.H.$v[a]:a?(_.Pb(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=null):a=Ir;if(a){var b;if("function"===typeof a)b=a(this);else{var c={};for(b in a){var d=a[b];c[b]="function"===typeof d?_.F.yz(a,d,this):d}b=c}for(var h in e)a=b[h],"function"===typeof a&&
Lr(this,e[h],_.F.yz(b,a))}f&&Lr(this,"close",f)});this.lk=this.ac=h;this.xG=(k||[]).slice();h&&this.xG.unshift(h.Ba())};vr.prototype.wc=function(){return this.hv};vr.prototype.Vi=function(){return this.params};vr.prototype.sy=function(){return this.methods};vr.prototype.Jd=function(){return this.lk};var Jr=function(a,b){if(!a.UA){var c=b&&!_.H.$v[b]&&_.H.hD[b];c?(a.gD=[],c(function(){a.UA=!0;for(var b=0,c=a.gD.length;b<c;++b)a.gD[b].call(a)})):a.UA=!0}},Kr=function(a,b){a.UA?b.call(a):a.gD.push(b)};
vr.prototype.Rd=function(a,b){Kr(this,function(){Lr(this,a,b)})};var Lr=function(a,b,c){a.Gs[b]=a.Gs[b]||[];a.Gs[b].push(c)};vr.prototype.jo=function(a,b){Kr(this,function(){var c=this.Gs[a];if(c)for(var d=0,e=c.length;d<e;++d)if(c[d]===b){c.splice(d,1);break}})};
vr.prototype.ei=function(a,b){var c,d=this.Gs[a];if(d)for(var e=Array.prototype.slice.call(arguments,1),f=0,h=d.length;f<h;++f)try{c=d[f].apply({},e)}catch(k){_.Ob(['Exception when calling callback "',a,'" with exception "',k.name,": ",k.message,'".'].join(""))}return c};
var Mr=function(a){return"number"==typeof a?{value:a,bE:a+"px"}:"100%"==a?{value:100,bE:"100%",eP:!0}:null},Nr=function(a,b,c,d,e,f,h){vr.call(this,a,b,c,d,Gr,e,f,h);this.id=b.id||er();this.Av=b.rpctoken&&String(b.rpctoken)||Math.round(1E9*(0,_.yk)());this.t2=tr(this.params,this.config);this.SD={};Kr(this,function(){this.ei("open");_.lr(this.SD,this)})};wr(Nr);_.g=Nr.prototype;
_.g.Jg=function(a,b){if(!this.config.url)return _.Ob("Cannot open iframe, empty URL."),this;var c=this.id;_.H.Fl[c]=this;var d=_.lr(this.methods);d._ready=this.Rz;d._close=this.close;d._open=this.Sz;d._resizeMe=this.Nq;d._renderstart=this.kQ;var e=this.t2;this.Av&&(e.rpctoken=this.Av);e._methods=_.nr(d,c,"",this,!0);this.Mx=a="string"===typeof a?window.document.getElementById(a):a;d={};d.id=c;if(b){d.attributes=b;var f=b.style;if("string"===typeof f){var h;if(f){h=[];for(var f=f.split(";"),k=0,l=
f.length;k<l;++k){var m=f[k];if(0!=m.length||k+1!=l)m=m.split(":"),2==m.length&&m[0].match(/^[ a-zA-Z_-]+$/)&&m[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?h.push(m.join(":")):_.Ob(['Iframe style "',f[k],'" not allowed.'].join(""))}h=h.join(";")}else h="";b.style=h}}this.wc().allowPost&&(d.allowPost=!0);d.queryParams=this.params;d.fragmentParams=e;d.paramsSerializer=fr;this.li=_.Gm(this.config.url,a,d);e=this.li.getAttribute("data-postorigin")||this.li.src;_.H.Fl[c]=this;_.G.EA(this.id,this.Av);_.G.rj(this.id,
e);return this};_.g.rf=function(a,b){this.SD[a]=b};_.g.Ba=function(){return this.id};_.g.kb=function(){return this.li};_.g.Jb=function(){return this.Mx};_.g.eg=function(a){this.Mx=a};_.g.Rz=function(a){var b=pr(a,this.id,"");this.lk&&"function"==typeof this.methods._ready&&(a._methods=_.nr(b,this.lk.Ba(),this.id,this,!1),this.methods._ready(a));_.lr(a,this);_.lr(b,this);this.ei("ready",a)};_.g.kQ=function(a){this.ei("renderstart",a)};
_.g.close=function(a){a=this.ei("close",a);delete _.H.Fl[this.id];return a};_.g.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.g.Sz=function(a){var b=pr(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.Mx);if(qr(a.openParams))new Or(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain);else{var c=new Nr(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain),d=this;Kr(c,function(){var a={childId:c.Ba()},f=c.SD;f._toclose=c.close;a._methods=_.nr(f,d.id,c.id,c,!1);b._onopen(a)})}};
_.g.Nq=function(a){if(void 0===this.ei("resize",a)&&this.li){var b=Mr(a.width);null!=b&&(this.li.style.width=b.bE);a=Mr(a.height);null!=a&&(this.li.style.height=a.bE);this.li.parentElement&&(null!=b&&b.eP||null!=a&&a.eP)&&(this.li.parentElement.style.display="block")}};
var Or=function(a,b,c,d,e,f,h){vr.call(this,a,b,c,d,Hr,e,f,h);this.url=a;this.Jo=null;this.WG=er();Kr(this,function(){var a;this.ei("beforeparentopen");var b=_.lr(this.methods);b._onopen=this.e5;b._ready=this.Rz;b._onclose=this.d5;this.params._methods=_.nr(b,"..",this.WG,this,!0);b={};for(a in this.params)b[a]=fr(this.params[a]);var c=this.config.url;if(this.hv.hideUrlFromParent){a=window.name;var d=c,c=_.lm(this.config.url,this.params,{},fr),e=b,b={};b._methods=e._methods;b["#opener"]=e["#opener"];
b["#urlindex"]=e["#urlindex"];b["#opener"]&&void 0!=e["#urlindex"]?(b["#opener"]=a+","+b["#opener"],a=d):(d=_.Pa(_.Za,"fUrl",[]),e=d.length,d[e]=c,_.Za.rUrl=Cr,b["#opener"]=a,b["#urlindex"]=e,a=_.rj.qb(_.Ia.location.href),c=_.E("iframes/relay_url_"+(0,window.encodeURIComponent)(a))||"/_/gapi/sibling/1/frame.html",a+=c);c=a}_.Uc._open({url:c,openParams:this.hv,params:b,proxyId:this.WG,openedByProxyChain:this.xG})})};wr(Or);Or.prototype.q0=function(){return this.Jo};
Or.prototype.e5=function(a){this.Jo=a.childId;var b=pr(a,"..",this.Jo);_.lr(b,this);this.close=b._toclose;_.H.Fl[this.Jo]=this;this.lk&&this.methods._onopen&&(a._methods=_.nr(b,this.lk.Ba(),this.Jo,this,!1),this.methods._onopen(a))};Or.prototype.Rz=function(a){var b=String(this.Jo),c=pr(a,"..",b);_.lr(a,this);_.lr(c,this);this.ei("ready",a);this.lk&&this.methods._ready&&(a._methods=_.nr(c,this.lk.Ba(),b,this,!1),this.methods._ready(a))};
Or.prototype.d5=function(a){if(this.lk&&this.methods._onclose)this.methods._onclose(a);else return a=this.ei("close",a),delete _.H.Fl[this.Jo],a};
var Pr=function(a,b,c,d,e,f,h){vr.call(this,a,b,c,d,Hr,f,h);this.id=b.id||er();this.C8=e;d._close=this.close;this.onClosed=this.YP;this.MT=0;Kr(this,function(){this.ei("beforeparentopen");var b=_.lr(this.methods);this.params._methods=_.nr(b,"..",this.WG,this,!0);b={};b.queryParams=this.params;a=_.xm(_.Ja,this.config.url,this.id,b);var c=e.openWindow(a);this.canAutoClose=function(a){a(e.uL(c))};e.pS(c,this);this.MT=c})};wr(Pr);
Pr.prototype.close=function(a){a=this.ei("close",a);this.C8.FL(this.MT);return a};Pr.prototype.YP=function(){this.ei("close")};
(function(){_.H.Fl={};_.H.$v={};_.H.hD={};_.H.CO=0;_.H.nA={};_.H.Sp={};_.H.Xz=null;_.H.Wz=[];_.H.n5=function(a){var b=!1;try{if(null!=a)var c=window.parent.frames[a.id],b=c.iframer.id==a.id&&c.iframes.openedId_(_.Uc.id)}catch(f){}try{_.H.Xz={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:b};for(a=0;a<_.H.Wz.length;++a)_.H.Wz[a](_.H.Xz);_.H.Wz=[]}catch(f){}};_.H.Y_=function(a){var b=a&&a.lk,c=null;b&&(c={},c.id=b.Ba(),c.proxyChain=
a.xG);return c};Er();if(window.parent!=window){var a=_.F.Xc();a.gcv&&ir(a.gcv);var b=a.jsh;b&&jr(b);_.lr(pr(a,"..",""),_.Uc);_.lr(a,_.Uc);Fr()}_.H.Ua=xr;_.H.Hc=yr;_.H.w7=Br;_.H.resize=Ar;_.H.f_=function(a){return _.H.hD[a]};_.H.QH=function(a,b){_.H.hD[a]=b};_.H.nR=Ar;_.H.P7=Br;_.H.My={};_.H.My.get=xr;_.H.My.set=yr;_.H.qX=function(a,b){mr(a);_.H.Sp[a]=b||window[a]};_.H.xha=function(a){delete _.H.Sp[a]};_.H.open=function(a,b,e,f,h,k){3==arguments.length?f={}:4==arguments.length&&"function"===typeof f&&
(h=f,f={});var c="bubble"===b.style&&zr?zr.Aa():null;return c?new Pr(a,b,e,f,c,h,k):qr(b)?new Or(a,b,e,f,h,k):new Nr(a,b,e,f,h,k)};_.H.close=function(a,b){_.Uc&&_.Uc._close&&_.Uc._close(a,b)};_.H.ready=function(a,b,e){2==arguments.length&&"function"===typeof b&&(e=b,b={});var c=a||{};"height"in c||(c.height=_.Ol.Vd());c._methods=_.nr(b||{},"..","",_.Uc,!0);_.Uc&&_.Uc._ready&&_.Uc._ready(c,e)};_.H.qN=function(a){_.H.Xz?a(_.H.Xz):_.H.Wz.push(a)};_.H.h5=function(a){return!!_.H.Fl[a]};_.H.q_=function(){return["https://ssl.gstatic.com/gb/js/",
_.E("googleapis.config/gcv")].join("")};_.H.PQ=function(a){var b={mouseover:1,mouseout:1};if(_.Uc._event)for(var c=0;c<a.length;c++){var f=a[c];f in b&&_.F.Ww(window.document,f,function(a){_.Uc._event({event:a.type,timestamp:(new Date).getTime()})},!0)}};_.H.D7=jr;_.H.NH=kr;_.H.uP=gr;_.H.EO=_.Uc})();
_.D("iframes.allow",_.H.qX);_.D("iframes.callSiblingOpener",_.H.TX);_.D("iframes.registerForOpenedSibling",_.H.V5);_.D("iframes.close",_.H.close);_.D("iframes.getGoogleConnectJsUri",_.H.q_);_.D("iframes.getHandler",_.H.Ua);_.D("iframes.getDeferredHandler",_.H.f_);_.D("iframes.getParentInfo",_.H.qN);_.D("iframes.iframer",_.H.EO);_.D("iframes.open",_.H.open);_.D("iframes.openedId_",_.H.h5);_.D("iframes.propagate",_.H.PQ);_.D("iframes.ready",_.H.ready);_.D("iframes.resize",_.H.resize);
_.D("iframes.setGoogleConnectJsVersion",_.H.w7);_.D("iframes.setBootstrapHint",_.H.NH);_.D("iframes.setJsHint",_.H.D7);_.D("iframes.setHandler",_.H.Hc);_.D("iframes.setDeferredHandler",_.H.QH);_.D("IframeBase",vr);_.D("IframeBase.prototype.addCallback",vr.prototype.Rd);_.D("IframeBase.prototype.getMethods",vr.prototype.sy);_.D("IframeBase.prototype.getOpenerIframe",vr.prototype.Jd);_.D("IframeBase.prototype.getOpenParams",vr.prototype.wc);_.D("IframeBase.prototype.getParams",vr.prototype.Vi);
_.D("IframeBase.prototype.removeCallback",vr.prototype.jo);_.D("Iframe",Nr);_.D("Iframe.prototype.close",Nr.prototype.close);_.D("Iframe.prototype.exposeMethod",Nr.prototype.rf);_.D("Iframe.prototype.getId",Nr.prototype.Ba);_.D("Iframe.prototype.getIframeEl",Nr.prototype.kb);_.D("Iframe.prototype.getSiteEl",Nr.prototype.Jb);_.D("Iframe.prototype.openInto",Nr.prototype.Jg);_.D("Iframe.prototype.remove",Nr.prototype.remove);_.D("Iframe.prototype.setSiteEl",Nr.prototype.eg);
_.D("Iframe.prototype.addCallback",Nr.prototype.Rd);_.D("Iframe.prototype.getMethods",Nr.prototype.sy);_.D("Iframe.prototype.getOpenerIframe",Nr.prototype.Jd);_.D("Iframe.prototype.getOpenParams",Nr.prototype.wc);_.D("Iframe.prototype.getParams",Nr.prototype.Vi);_.D("Iframe.prototype.removeCallback",Nr.prototype.jo);_.D("IframeProxy",Or);_.D("IframeProxy.prototype.getTargetIframeId",Or.prototype.q0);_.D("IframeProxy.prototype.addCallback",Or.prototype.Rd);_.D("IframeProxy.prototype.getMethods",Or.prototype.sy);
_.D("IframeProxy.prototype.getOpenerIframe",Or.prototype.Jd);_.D("IframeProxy.prototype.getOpenParams",Or.prototype.wc);_.D("IframeProxy.prototype.getParams",Or.prototype.Vi);_.D("IframeProxy.prototype.removeCallback",Or.prototype.jo);_.D("IframeWindow",Pr);_.D("IframeWindow.prototype.close",Pr.prototype.close);_.D("IframeWindow.prototype.onClosed",Pr.prototype.YP);_.D("iframes.util.getTopMostAccessibleWindow",_.H.Wa.FN);_.D("iframes.handlers.get",_.H.My.get);_.D("iframes.handlers.set",_.H.My.set); _.D("iframes.resizeMe",_.H.nR);_.D("iframes.setVersionOverride",_.H.P7);
vr.prototype.send=function(a,b,c){_.H.KR(this,a,b,c)};_.Uc.send=function(a,b,c){_.H.KR(_.Uc,a,b,c)};vr.prototype.register=function(a,b){var c=this;c.Rd(a,function(a){b.call(c,a)})};_.H.KR=function(a,b,c,d){var e=[];void 0!==c&&e.push(c);d&&e.push(function(a){d.call(this,[a])});a[b]&&a[b].apply(a,e)};_.H.Sr=function(){return!0};_.D("iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.H.Sr);_.D("IframeBase.prototype.send",vr.prototype.send);_.D("IframeBase.prototype.register",vr.prototype.register);
_.D("Iframe.prototype.send",Nr.prototype.send);_.D("Iframe.prototype.register",Nr.prototype.register);_.D("IframeProxy.prototype.send",Or.prototype.send);_.D("IframeProxy.prototype.register",Or.prototype.register);_.D("IframeWindow.prototype.send",Pr.prototype.send);_.D("IframeWindow.prototype.register",Pr.prototype.register);_.D("iframes.iframer.send",_.H.EO.send);

}catch(e){_._DumpException(e)}
try{
_.F=_.F||{};
(function(){function a(b){var c="";if(3==b.nodeType||4==b.nodeType)c=b.nodeValue;else if(b.innerText)c=b.innerText;else if(b.innerHTML)c=b.innerHTML;else if(b.firstChild){c=[];for(b=b.firstChild;b;b=b.nextSibling)c.push(a(b));c=c.join("")}return c}_.F.createElement=function(a){var b;if(!window.document.body||window.document.body.namespaceURI)try{b=window.document.createElementNS("http://www.w3.org/1999/xhtml",a)}catch(d){}return b||window.document.createElement(a)};_.F.VC=function(a){var b=_.F.createElement("iframe");
try{var d=["<","iframe"],e=a||{},f;for(f in e)e.hasOwnProperty(f)&&(d.push(" "),d.push(f),d.push('="'),d.push(_.F.Xx(e[f])),d.push('"'));d.push("></");d.push("iframe");d.push(">");var h=_.F.createElement(d.join(""));h&&(!b||h.tagName==b.tagName&&h.namespaceURI==b.namespaceURI)&&(b=h)}catch(l){}d=b;a=a||{};for(var k in a)a.hasOwnProperty(k)&&(d[k]=a[k]);return b};_.F.ey=function(){if(window.document.body)return window.document.body;try{var a=window.document.getElementsByTagNameNS("http://www.w3.org/1999/xhtml", "body");if(a&&1==a.length)return a[0]}catch(c){}return window.document.documentElement||window.document};_.F.Lha=function(b){return a(b)}})();

}catch(e){_._DumpException(e)}
try{
_.Hj=function(){return Math.floor((new Date).getTime()/1E3)};var Jj,Kj;_.Ij=function(a,b){this.yc=a;var c=b||{};this.X3=Number(c.maxAge)||0;this.Wf=c.domain;this.pk=c.path;this.U6=!!c.secure};Jj=/^[-+/_=.:|%&a-zA-Z0-9@]*$/;Kj=/^[A-Z_][A-Z0-9_]{0,63}$/;_.Ij.prototype.read=function(){for(var a=this.yc+"=",b=window.document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c];if(0==d.indexOf(a))return d.substr(a.length)}};
_.Ij.prototype.write=function(a,b){if(!Kj.test(this.yc))throw"Invalid cookie name";if(!Jj.test(a))throw"Invalid cookie value";var c=this.yc+"="+a;this.Wf&&(c+=";domain="+this.Wf);this.pk&&(c+=";path="+this.pk);var d="number"===typeof b?b:this.X3;if(0<=d){var e=new Date;e.setSeconds(e.getSeconds()+d);c+=";expires="+e.toUTCString()}this.U6&&(c+=";secure");window.document.cookie=c;return!0};_.Ij.prototype.clear=function(){this.write("",0)}; _.Ij.iterate=function(a){for(var b=window.document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c].split("="),e=d.shift();a(e,d.join("="))}};
var Mj;_.Lj=function(a){this.bj=a};Mj={};_.Lj.prototype.read=function(){if(Mj.hasOwnProperty(this.bj))return Mj[this.bj]};_.Lj.prototype.write=function(a){Mj[this.bj]=a;return!0};_.Lj.prototype.clear=function(){delete Mj[this.bj]};_.Lj.iterate=function(a){for(var b in Mj)Mj.hasOwnProperty(b)&&a(b,Mj[b])};
var Nj,Oj;Nj=function(){this.Sa=null;this.key=function(){return null};this.getItem=function(){return this.Sa};this.setItem=function(a,b){this.Sa=b;this.length=1};this.removeItem=function(){this.clear()};this.clear=function(){this.Sa=null;this.length=0};this.length=0};Oj=function(a){try{var b=a||window.sessionStorage;if(!b)return!1;b.setItem("gapi.sessionStorageTest","gapi.sessionStorageTest"+b.length);b.removeItem("gapi.sessionStorageTest");return!0}catch(c){return!1}};
_.Pj=function(a,b){this.yc=a;this.CI=Oj(b)?b||window.sessionStorage:new Nj};_.Pj.prototype.read=function(){return this.CI.getItem(this.yc)};_.Pj.prototype.write=function(a){try{this.CI.setItem(this.yc,a)}catch(b){return!1}return!0};_.Pj.prototype.clear=function(){this.CI.removeItem(this.yc)};_.Pj.iterate=function(a){if(Oj())for(var b=0,c=window.sessionStorage.length;b<c;++b){var d=window.sessionStorage.key(b);a(d,window.sessionStorage[d])}};
for(var Qj=0;64>Qj;++Qj);_.Rj="https:"===window.location.protocol;_.Sj=_.Rj||"http:"===window.location.protocol?_.Ij:_.Lj;_.Tj=function(a){var b=a.substr(1),c="",d=window.location.hostname;if(""!==b){c=(0,window.parseInt)(b,10);if((0,window.isNaN)(c))return null;b=d.split(".");if(b.length<c-1)return null;b.length==c-1&&(d="."+d)}else d="";return{qd:"S"==a.charAt(0),domain:d,Bg:c}};
var Uj;Uj=[".APPS.GOOGLEUSERCONTENT.COM","@DEVELOPER.GSERVICEACCOUNT.COM"];_.Vj=function(a){a=a.toUpperCase();for(var b=0,c=Uj.length;b<c;++b){var d=a.split(Uj[b]);2==d.length&&""===d[1]&&(a=d[0])}a=a.replace(/-/g,"_").toUpperCase();40<a.length&&(b=new _.Gj,b.XI(a),a=b.Ri().toUpperCase());return a};
_.Wj=function(a){if(0!==a.indexOf("GCSC"))return null;var b={Je:!1};a=a.substr(4);if(!a)return b;var c=a.charAt(0);a=a.substr(1);var d=a.lastIndexOf("_");if(-1==d)return b;var e=_.Tj(a.substr(d+1));if(null==e)return b;a=a.substring(0,d);if("_"!==a.charAt(0))return b;d="E"===c&&e.qd;return!d&&("U"!==c||e.qd)||d&&!_.Rj?b:{Je:!0,qd:d,CL:a.substr(1),domain:e.domain,Bg:e.Bg}};
var Xj,Yj,ck,dk,gk;Xj=_.Ra();Yj=_.Ra();_.Zj=_.Ra();_.ak=_.Ra();_.bk=null;ck="state code cookie_policy g_user_cookie_policy authuser prompt g-oauth-window status".split(" ");dk=function(a){this.JG=a;this.SF=null};dk.prototype.write=function(a){var b=_.Ra(),c=_.Ra(),d;for(d in a)_.Sa(a,d)&&(c[d]=a[d],b[d]=a[d]);d=0;for(var e=ck.length;d<e;++d)delete c[ck[d]];a=String(a.authuser||0);d=_.Ra();d[a]=_.F.Xc("#"+_.ek(c));this.JG.write((0,_.gc)(d));this.SF=b};dk.prototype.read=function(){return this.SF};
dk.prototype.clear=function(){this.JG.clear();this.SF=_.Ra()};
_.fk=function(a){if(!a)return null;"single_host_origin"!==a&&(a=_.G.qb(a));var b=window.location.hostname,c=b,d=_.Rj;if("single_host_origin"!==a){c=a.split("://");if(2==c.length)d="https"===c.shift();else return _.Yb("WARNING invalid cookie_policy: "+a),null;c=c[0]}if(-1!==c.indexOf(":"))c=b="";else{a="."+c;if(b.lastIndexOf(a)!==b.length-a.length)return _.Yb("Invalid cookie_policy domain: "+c),null;c=a;b=c.split(".").length-1}return{domain:c,qd:d,Bg:b}};
gk=function(a){if(!a)return null;var b=a.client_id;if(!b)return null;b=_.Vj(b);a=_.fk(a.cookie_policy);return a?!_.Rj&&a.qd?(_.Yb("WARNING: https cookie_policy set for http domain"),null):["GCSC",a.qd?"E":"U","_",b,"_",a.qd?"S":"H",a.Bg].join(""):null};_.hk=function(a){return a?{domain:a.domain,path:"/",secure:a.qd}:null};_.ik=function(a){var b=Xj[a];b||(b=new dk(new _.Lj(a)),Xj[a]=b);return{yh:b,key:a}};
_.jk=function(a,b){var c=b?Yj:Xj,d=b?_.Sj:_.Pj,e=a&&gk(a),f=!!e;a&&!a.g_user_cookie_policy&&(d=_.Lj,e="token");if(!e)if(!b&&_.bk)e=_.bk;else return null;var h=c[e];if(!h){h=_.Wj(e);if(!("token"===e||h&&h.Je))return null;h=new d(e,_.hk(h));b||(h=new dk(h))}c[e]=h;return{yh:h,key:e,GZ:f}};
_.kk=function(a,b,c){a=a&&"token"!==a?_.ik(a):_.jk();if(!a)return null;if(c){c=a.yh;_.Ra();var d=c.JG.read();c=null;try{c=(0,_.hc)(d)}catch(e){}0==c&&(c=null);d=_.xj()||"0";d=String(d);c=c&&c[d]}else c=a.yh.read();c&&c.expires_at&&_.Hj()>c.expires_at&&(a.yh.clear(),c=null);c&&c.error&&!b&&(c=null);return c};
_.ek=function(a){var b="";if(!a)return b;for(var c in a)if({}.hasOwnProperty.call(a,c)){var d;d=a[c];if(null!=d){var e=[(0,window.encodeURIComponent)(c),"="];if(d instanceof Array){for(var f=[],h=0;h<d.length;h++)f.push((0,window.encodeURIComponent)(d[h]));e.push(f.join("+"))}else e.push((0,window.encodeURIComponent)(d));d=e.join("")}else d="";d&&(b&&(b+="&"),b+=d)}return b};_.Pj.iterate(function(a){var b=_.Wj(a);b&&b.Je&&(Xj[a]=new dk(new _.Pj(a)))}); _.Sj.iterate(function(a){Xj[a]&&(Yj[a]=new _.Sj(a,_.hk(_.Wj(a))))});

}catch(e){_._DumpException(e)}
try{
_.uj=window.googleapis&&window.googleapis.server||{};
}catch(e){_._DumpException(e)}
try{
_.lk=function(){var a=/\s*;\s*/;return{get:function(b,c){for(var d=b+"=",e=(window.document.cookie||"").split(a),f=0,h;h=e[f];++f)if(0==h.indexOf(d))return h.substr(d.length);return c}}}();
}catch(e){_._DumpException(e)}
try{
_.Vc=function(a){var b=_.pa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.Wc=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.Xc=function(a){return"number"==typeof a};_.Yc=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.Zc=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.$c=2147483648*Math.random()|0;
}catch(e){_._DumpException(e)}
try{
var dd;_.ad=function(a){return/^[\s\xa0]*$/.test(a)};_.bd=function(a,b){return 0==a.lastIndexOf(b,0)};_.cd=function(a){return null==a?"":String(a)};dd=0;_.ed=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};_.fd=function(a){return a[_.ta]||(a[_.ta]=++dd)};_.gd=function(a){return"function"==_.pa(a)};
_.hd=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.id=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.t(a))return _.t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.jd=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.kd=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.t(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var l=h[k];b.call(c,l,k,a)&&(e[f++]=l)}return e};_.ld=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
_.md=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.nd=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};_.pd=function(a,b){return 0<=(0,_.hd)(a,b)};
_.rd=function(a,b){var c=(0,_.hd)(a,b),d;(d=0<=c)&&_.qd(a,c);return d};_.qd=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.sd=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.Vc(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}};

}catch(e){_._DumpException(e)}
try{
var nk,ok;_.mk=function(a){this.Db=a||{cookie:""}};nk=/\s*;\s*/;_.g=_.mk.prototype;_.g.isEnabled=function(){return window.navigator.cookieEnabled};_.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("D`"+a);if(/[;\r\n]/.test(b))throw Error("E`"+b);_.na(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.Ca)()+1E3*c)).toUTCString();this.Db.cookie=a+"="+b+e+d+c+f};
_.g.get=function(a,b){for(var c=a+"=",d=(this.Db.cookie||"").split(nk),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.g.remove=function(a,b,c){var d=this.Pi(a);this.set(a,"",0,b,c);return d};_.g.tf=function(){return ok(this).keys};_.g.Wd=function(){return ok(this).values};_.g.isEmpty=function(){return!this.Db.cookie};_.g.Yb=function(){return this.Db.cookie?(this.Db.cookie||"").split(nk).length:0};_.g.Pi=function(a){return _.na(this.get(a))};
_.g.Qm=function(a){for(var b=ok(this).values,c=0;c<b.length;c++)if(b[c]==a)return!0;return!1};_.g.clear=function(){for(var a=ok(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};ok=function(a){a=(a.Db.cookie||"").split(nk);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};_.pk=new _.mk("undefined"==typeof window.document?null:window.document);_.pk.Bca=3950;

}catch(e){_._DumpException(e)}
try{
var qk=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;n=m=0}function b(a){for(var b=h,c=0;64>c;c+=4)b[c/4]=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];for(c=16;80>c;c++)a=b[c-3]^b[c-8]^b[c-14]^b[c-16],b[c]=(a<<1|a>>>31)&4294967295;a=e[0];for(var d=e[1],f=e[2],k=e[3],l=e[4],m,p,c=0;80>c;c++)40>c?20>c?(m=k^d&(f^k),p=1518500249):(m=d^f^k,p=1859775393):60>c?(m=d&f|k&(d|f),p=2400959708):(m=d^f^k,p=3395469782),m=((a<<5|a>>>27)&4294967295)+m+l+p+b[c]&4294967295,
l=k,k=f,f=(d<<30|d>>>2)&4294967295,d=a,a=m;e[0]=e[0]+a&4294967295;e[1]=e[1]+d&4294967295;e[2]=e[2]+f&4294967295;e[3]=e[3]+k&4294967295;e[4]=e[4]+l&4294967295}function c(a,c){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var d=[],e=0,h=a.length;e<h;++e)d.push(a.charCodeAt(e));a=d}c||(c=a.length);d=0;if(0==m)for(;d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64;for(;d<c;)if(f[m++]=a[d++],n++,64==m)for(m=0,b(f);d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64}function d(){var a=[],
d=8*n;56>m?c(k,56-m):c(k,64-(m-56));for(var h=63;56<=h;h--)f[h]=d&255,d>>>=8;b(f);for(h=d=0;5>h;h++)for(var l=24;0<=l;l-=8)a[d++]=e[h]>>l&255;return a}for(var e=[],f=[],h=[],k=[128],l=1;64>l;++l)k[l]=0;var m,n;a();return{reset:a,update:c,digest:d,Ri:function(){for(var a=d(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b}}};
var sk=function(a,b,c){var d=[],e=[];if(1==(_.qa(c)?2:1))return e=[b,a],(0,_.jd)(d,function(a){e.push(a)}),rk(e.join(" "));var f=[],h=[];(0,_.jd)(c,function(a){h.push(a.key);f.push(a.value)});c=Math.floor((new Date).getTime()/1E3);e=0==f.length?[c,b,a]:[f.join(":"),c,b,a];(0,_.jd)(d,function(a){e.push(a)});a=rk(e.join(" "));a=[c,a];0==h.length||a.push(h.join(""));return a.join("_")},rk=function(a){var b=qk();b.update(a);return b.Ri().toLowerCase()};
var uk;_.tk=function(a){var b={SAPISIDHASH:!0,APISIDHASH:!0};return a&&(a.OriginToken||a.Authorization&&b[String(a.Authorization).split(" ")[0]])?!0:!1};uk=function(){var a=_.r.__OVERRIDE_SID;null==a&&(a=(new _.mk(window.document)).get("SID"));return!!a};
_.vk=function(a){var b=_.tj(String(_.r.location.href));if(uk()){var c=0==b.indexOf("https:")||0==b.indexOf("chrome-extension:"),b=c?_.r.__SAPISID:_.r.__APISID;null==b&&(b=(new _.mk(window.document)).get(c?"SAPISID":"APISID"));if(b){var c=c?"SAPISIDHASH":"APISIDHASH",d=String(_.r.location.href);return d&&b&&c?[c,sk(_.tj(d),b,a||null)].join(" "):null}}return null};
_.wk={i2:_.tk,p3:uk,a0:function(){var a=null;uk()&&(a=window.__PVT,null==a&&(a=_.lk.get("BEAT")));return a},fE:_.vk};
}catch(e){_._DumpException(e)}
try{
_.Nh=function(a){return(0,window.encodeURIComponent)(String(a))};_.Oh=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;_.Ph=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};_.Qh=function(a,b,c){if(_.qa(b))for(var d=0;d<b.length;d++)_.Qh(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",_.Nh(b))}; _.Rh=function(a,b){for(var c in b)_.Qh(c,b[c],a);return a};

}catch(e){_._DumpException(e)}
try{
var zk;zk=function(a,b){var c=_.F.VC({id:a,name:a});c.style.width="1px";c.style.height="1px";c.style.position="absolute";c.style.top="-100px";var d;if(window.navigator){d=window.navigator.userAgent||"";var e=window.navigator.product||"";d=0!=d.indexOf("Opera")&&-1==d.indexOf("WebKit")&&"Gecko"==e&&0<d.indexOf("rv:1.")}else d=!1;c.src=d?"about:blank":b;c.tabIndex=-1;window.document.body.appendChild(c);d&&(c.src=b);return c};
_.Ak=function(){function a(){return!!h("auth/useFirstPartyAuthV2")}function b(a,b,c,d){var e=h("proxy");if(c||!e)var e=h("root"),f=h("root-1p")||e,e=e||"https://content.googleapis.com",f=f||"https://clients6.google.com",k=h("xd3")||"/static/proxy.html",e=(c||String(b?f:e))+k;e=String(e);(b=_.F.Xc().jsh||_.rj.qC.gN())&&(e+=(0<=e.indexOf("?")?"&":"?")+"jsh="+(0,window.encodeURIComponent)(b));h("push")&&(e+=(0<=e.indexOf("?")?"&":"?")+"p=1");e+="#parent="+(0,window.encodeURIComponent)(null!=d?String(d):
_.rj.qb(window.document.location.href));return e+("&rpctoken="+a)}function c(a,b,c,d){var h=e(c,d);l[h]||(c=zk(h,b),_.G.register("ready:"+a,function(){_.G.unregister("ready:"+a);if(!m[h]){m[h]=!0;var b=n[h];n[h]=[];for(var c=0,d=b.length;c<d;++c){var e=b[c];f(e.vo,e.q6,e.je)}}}),_.G.Mv(h,b),l[h]=c)}function d(a,d){var e=String(2147483647*(0,_.yk)()|0),f=b(e,a,d);_.jc(function(){c(e,f,a,d)})}function e(a,c){var d=b("",a,c,""),e=k[d];e||(e=_.xk(),e.update(d),e=e.Ri().toLowerCase(),e+=Math.random(),
k[d]=e);return"apiproxy"+e}function f(a,b,c){var f=void 0,h=!1;if("makeHttpRequests"!==a)throw'only "makeHttpRequests" RPCs are implemented';var k=function(a){if(a){if("undefined"!=typeof f&&"undefined"!=typeof a.root&&f!=a.root)throw"all requests in a batch must have the same root URL";f=a.root||f;h=_.wk.i2(a.headers)}};if(b)for(var p=0,v=b.length;p<v;++p){var x=b[p];x&&k(x.params)}var K=e(h,f);l[K]||d(h,f);m[K]?_.G.call(K,a,function(a){if(this.f==K&&this.t==_.G.ql(this.f)&&this.origin==_.G.zl(this.f)){var b=
(0,_.hc)(a);c(b,a)}},b):(n[K]||(n[K]=[]),n[K].push({vo:a,q6:b,je:c}))}function h(a){return _.E("googleapis.config/"+a)}var k={},l={},m={},n={};return{UK:function(b,c,d){var e=d||"auto";b=b||{};if("none"==e)return b;c=c||window.location.href;d=b.Authorization;var f=b.OriginToken;if(!d&&!f){f=_.kk(void 0,void 0);!f&&window.gapi.auth2&&"function"==typeof window.gapi.auth2._gt&&(f=window.gapi.auth2._gt());f&&f.access_token&&("oauth2"==e||"auto"==e)&&(d=String(f.token_type||"Bearer")+" "+f.access_token);
if(f=!d)f=(!!h("auth/useFirstPartyAuth")||"1p"==e)&&"oauth2"!=e;if(f&&_.wk.p3()){if(a()){d=h("primaryEmail");var e=h("appDomain"),f=h("fogId"),k=[];d&&k.push({key:"e",value:d});e&&k.push({key:"a",value:e});f&&k.push({key:"u",value:f});d=_.wk.fE(k)}else d=_.wk.fE();d&&(c=_.google.BE(c),c=b["X-Goog-AuthUser"]||c,_.ad(_.cd(c))&&(!a()||a()&&_.ad(_.cd(h("primaryEmail")))&&_.ad(_.cd(h("appDomain")))&&_.ad(_.cd(h("fogId"))))&&(c="0"),_.ad(_.cd(c))||(b["X-Goog-AuthUser"]=c))}d?b.Authorization=d:!1!==h("auth/useOriginToken")&& (f=_.wk.a0())&&(b.OriginToken=f)}return b},Xq:f}}();

}catch(e){_._DumpException(e)}
try{
var Bk=["appVersion","platform","userAgent"],Ck=function(a){if(a&&window.navigator){for(var b=[],c=0;c<Bk.length;c++){var d=window.navigator[Bk[c]];d&&b.push((0,window.encodeURIComponent)(Bk[c])+"="+(0,window.encodeURIComponent)(d))}a["X-ClientDetails"]=b.join("&")}},Dk=function(a){return{execute:function(b){var c={};if(a.headers)for(var d in a.headers)Object.prototype.hasOwnProperty.call(a.headers,d)&&(c[d]=a.headers[d]);c=_.Ak.UK(c);Ck(c);var e={},f=a.urlParams;if(f)for(d in f)Object.hasOwnProperty.call(f,
d)&&(e[d]=f[d]);d=_.E("googleapis.config/developerKey");(d=_.E("client/apiKey",d))&&!e.key&&(e.key=String(d));(d=_.E("client/trace"))&&!e.trace&&(e.trace=String(d));_.Ak.Xq("makeHttpRequests",[{key:"googleapisRequest",params:{id:"googleapisRequest",key:"googleapisRequest",clientVersion:"1.0.0-alpha",httpMethod:a.httpMethod||"GET",root:a.root,url:a.url,urlParams:e,headers:c,body:a.body}}],function(a){return function(b){a(b.googleapisRequest.data)}}(b))}}},Ek=function(a,b){return function(c){var d=
{};c=c.body;var e=(0,_.hc)(c),f={};if(e&&e.length)for(var h=0,k=e.length;h<k;++h){var l=e[h];f[l.id]=l}h=0;for(k=b.length;h<k;++h)l=b[h].id,d[l]=e&&e.length?f[l]:e;a(d,c)}},Fk=function(a,b){a.transport={name:"googleapis",execute:function(b,d){for(var c=[],f=0,h=b.length;f<h;++f){var k=b[f],l=k.method,m=String(l).split(".")[0],m=_.E("googleapis.config/versions/"+l)||_.E("googleapis.config/versions/"+m)||"v1";c.push({jsonrpc:"2.0",id:k.id,method:l,apiVersion:String(m),params:k.params})}f=Dk({httpMethod:"POST",
root:a.transport.root,url:"/rpc?pp=0",headers:{"Content-Type":"application/json"},body:c});f.execute.call(f,Ek(d,c))},root:b}},Gk=function(a){var b=this.method,c=this.transport;c.execute.call(c,[{method:b,id:b,params:this.rpc}],function(c){c=c[b];c.error||(c=c.data||c.result);a(c)})},Hk=function(a,b,c){a={method:a,rpc:b||{}};Fk(a,c);a.execute=Gk;return a},Ik=function(a,b){for(var c=a.split("."),d=function(c){c=c||{};c.groupId=c.groupId||"@self";c.userId=c.userId||"@viewer";return Hk(a,c,b)},e=_.r,
f=0,h=c.length;f<h;++f){var k=e[c[f]]||{};f+1==h&&(k=d);e=e[c[f]]=k}if(1<c.length&&"googleapis"!=c[0])for(c[0]="googleapis","delete"==c[c.length-1]&&(c[c.length-1]="remove"),e=_.r,f=0,h=c.length;f<h;++f)k=e[c[f]]||{},f+1==h&&(k=d),e=e[c[f]]=k},Jk;for(Jk in _.E("googleapis.config/methods"))Ik(Jk);
_.D("googleapis.newRequest",function(a,b,c){return Hk(a,b,c)});_.D("googleapis.newHttpRequest",function(a){return Dk(a)});_.D("googleapis.register",function(a,b){Ik(a,b)});_.D("googleapis.setUrlParameter",function(a,b){if("trace"!==a)throw Error("F");_.hb("client/trace",b)});_.D("googleapis.setDeveloperKey",function(a){_.hb("googleapis.config/developerKey",a);_.hb("client/apiKey",a)});_.D("googleapis.setVersions",function(a){_.hb("googleapis.config/versions",a)});

}catch(e){_._DumpException(e)}
})(this._);
// Google Inc.
